{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ad5b9e9b-12ae-4606-86e9-5ffefeea6e58",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "class Calculator:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Calculator\")\n",
    "        self.root.geometry(\"400x600\")\n",
    "        self.root.resizable(False, False)\n",
    "        self.root.configure(bg='#2b2b2b')\n",
    "        \n",
    "        self.expression = \"\"\n",
    "        self.result_var = tk.StringVar()\n",
    "        \n",
    "        # Display\n",
    "        self.create_display()\n",
    "        \n",
    "        # Buttons\n",
    "        self.create_buttons()\n",
    "    \n",
    "    def create_display(self):\n",
    "        display_frame = tk.Frame(self.root, bg='#2b2b2b')\n",
    "        display_frame.pack(expand=True, fill='both')\n",
    "        \n",
    "        self.display = tk.Entry(\n",
    "            display_frame,\n",
    "            textvariable=self.result_var,\n",
    "            font=('Arial', 32, 'bold'),\n",
    "            bd=0,\n",
    "            bg='#2b2b2b',\n",
    "            fg='white',\n",
    "            justify='right'\n",
    "        )\n",
    "        self.display.pack(expand=True, fill='both', padx=20, pady=20)\n",
    "        self.result_var.set(\"0\")\n",
    "    \n",
    "    def create_buttons(self):\n",
    "        button_frame = tk.Frame(self.root, bg='#2b2b2b')\n",
    "        button_frame.pack(expand=True, fill='both')\n",
    "        \n",
    "        # Button layout like a real calculator\n",
    "        buttons = [\n",
    "            ['C', '⌫', '%', '/'],\n",
    "            ['7', '8', '9', '*'],\n",
    "            ['4', '5', '6', '-'],\n",
    "            ['1', '2', '3', '+'],\n",
    "            ['±', '0', '.', '=']\n",
    "        ]\n",
    "        \n",
    "        for i, row in enumerate(buttons):\n",
    "            for j, button in enumerate(row):\n",
    "                self.create_button(button_frame, button, i, j)\n",
    "    \n",
    "    def create_button(self, frame, text, row, col):\n",
    "        # Color scheme\n",
    "        if text in ['C', '⌫', '%', '±']:\n",
    "            bg_color = '#505050'\n",
    "            fg_color = 'white'\n",
    "        elif text in ['/', '*', '-', '+', '=']:\n",
    "            bg_color = '#ff9500'\n",
    "            fg_color = 'white'\n",
    "        else:\n",
    "            bg_color = '#3a3a3a'\n",
    "            fg_color = 'white'\n",
    "        \n",
    "        button = tk.Button(\n",
    "            frame,\n",
    "            text=text,\n",
    "            font=('Arial', 20, 'bold'),\n",
    "            bg=bg_color,\n",
    "            fg=fg_color,\n",
    "            bd=0,\n",
    "            activebackground='#4a4a4a',\n",
    "            command=lambda: self.on_button_click(text)\n",
    "        )\n",
    "        \n",
    "        button.grid(row=row, column=col, sticky='nsew', padx=2, pady=2)\n",
    "        frame.grid_rowconfigure(row, weight=1)\n",
    "        frame.grid_columnconfigure(col, weight=1)\n",
    "    \n",
    "    def on_button_click(self, char):\n",
    "        if char == 'C':\n",
    "            self.expression = \"\"\n",
    "            self.result_var.set(\"0\")\n",
    "        \n",
    "        elif char == '⌫':\n",
    "            self.expression = self.expression[:-1]\n",
    "            self.result_var.set(self.expression if self.expression else \"0\")\n",
    "        \n",
    "        elif char == '=':\n",
    "            try:\n",
    "                result = eval(self.expression)\n",
    "                self.result_var.set(str(result))\n",
    "                self.expression = str(result)\n",
    "            except:\n",
    "                self.result_var.set(\"Error\")\n",
    "                self.expression = \"\"\n",
    "        \n",
    "        elif char == '±':\n",
    "            if self.expression:\n",
    "                try:\n",
    "                    result = eval(self.expression)\n",
    "                    result = -result\n",
    "                    self.expression = str(result)\n",
    "                    self.result_var.set(self.expression)\n",
    "                except:\n",
    "                    pass\n",
    "        \n",
    "        elif char == '%':\n",
    "            try:\n",
    "                result = eval(self.expression) / 100\n",
    "                self.expression = str(result)\n",
    "                self.result_var.set(self.expression)\n",
    "            except:\n",
    "                pass\n",
    "        \n",
    "        else:\n",
    "            if self.expression == \"0\":\n",
    "                self.expression = char\n",
    "            else:\n",
    "                self.expression += char\n",
    "            self.result_var.set(self.expression)\n",
    "\n",
    "# Run the calculator\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    calc = Calculator(root)\n",
    "    root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b56356c-9635-4928-ae51-81a5ae324733",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
